### ISSUE TITLE
trouble in using scootplayer

### ISSUE THREAD

**Issue by maherfateh** [broadbent/scootplayer#7]
Hi 
when i tried the command:  maher@ubuntu:~/scootplayer$ python scootplayer.py -m 192.168.43.162/smart/smart.mpd
I've got this error:
Traceback (most recent call last):
  File "scootplayer.py", line 5, in <module>
    import scootplayer.player as player
  File "/home/maher/scootplayer/scootplayer/player.py", line 6, in <module>
    import requests
ImportError: No module named requests
so could you please help me to overcome this issue....
Thank you.

**Comment by janev94** [comment]
I realise that's an almost 3 year old thread but if someone has that issue, can you please confirm that you have installed the requirements for the project from requirements.txt. I.e. run pip install -r requirements.txt
